# Generated by Django 3.1 on 2020-08-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0002_auto_20200815_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiary',
            old_name='start_datec',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='apiary',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='colony',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='colony',
            name='death_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='colony',
            name='parent_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colony.colony'),
        ),
        migrations.AlterField(
            model_name='colony',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hive',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='hive_colony_map',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
