# Generated by Django 3.1 on 2020-08-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0004_auto_20200822_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='apiary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colony.apiary', verbose_name='Apiary'),
        ),
    ]
