# Generated by Django 3.1 on 2020-08-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0006_apiary_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='hive',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
