# Generated by Django 3.1 on 2020-09-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0007_auto_20200831_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiary',
            options={'verbose_name': 'Apiary', 'verbose_name_plural': 'Apiaries'},
        ),
        migrations.AlterModelOptions(
            name='hive',
            options={'verbose_name': 'Hive', 'verbose_name_plural': 'Hives'},
        ),
    ]
